### Locally load admin into user cache (if not already loaded)
GET {{baseUrl}}/user/v1/user-info
Authorization: Bearer {{$auth.token("admin")}}
Content-Type: application/json

> {%
  client.test("Get producer users", function () {
    client.assert(response.status === 200, "Expected Response status is 200, got: " + response.status)
    client.assert(response.body !== null, "Expected Response results to contain products")
  })
%}

### Create a new data request draft
POST {{baseUrl}}/agreement/v1/data-requests
Authorization: Bearer {{$auth.token("consumer")}}
Content-Type: application/json

{
  "title": {
    "de": "test data request",
    "fr": "test data request"
  },
  "description": {
    "de": "test data request description"
  }
}

> {%
  client.test("Create a new data request", function () {
    client.assert(response.status === 201, "Expected Response status is 201, got: " + response.status)
    client.assert(response.body.id !== null, "Expected Response results to contain an id")
    client.global.set("dataRequestId", response.body.id)
  })
%}

### GET products
GET {{baseUrl}}/products/v1
Authorization: Bearer {{$auth.token("consumer")}}
Content-Type: application/json

> {%
  client.test("Create a new data request", function () {
    client.assert(response.status === 200, "Expected Response status is 200, got: " + response.status)
    client.assert(response.body.length > 0, "Expected more than one products")
    client.global.set("productId", response.body[0].id)
    client.global.set("productId2", response.body[1].id)
    client.global.set("productId3", response.body[2].id)

  })
%}

### update data request with complete data
PUT {{baseUrl}}/agreement/v1/data-requests/{{dataRequestId}}
Authorization: Bearer {{$auth.token("consumer")}}
Content-Type: application/json

{
  "description": {
    "de": "test data request description",
    "fr": "test data request description",
    "it": "test data request description"
  },
  "products": [
    "{{productId}}"
  ],
  "title": {
    "de": "test data request",
    "fr": "test data request",
    "it": "test data request"
  },
  "purpose": {
    "de": "test purpose",
    "fr": "test purpose",
    "it": "test purpose"
  },
  "dataConsumerDisplayName": "Bio Suisse",
  "dataConsumerUid": 106506215,
  "dataConsumerCity": "Basel",
  "dataConsumerZip": "4052",
  "dataConsumerStreet": "Peter Merian-Str. 34",
  "dataConsumerCountry": "CH",
  "contactEmailAddress": "test@biosuisse.ch",
  "contactPhoneNumber": "+41 61 555 55 55",
  "targetGroup": "Bio Suisse Mitglieder"
}

> {%
  client.test("Create a new data request", function () {
    client.assert(response.status === 200, "Expected 200, got: " + response.status)
  })
%}

### set data request to in review
PUT {{baseUrl}}/agreement/v1/data-requests/{{dataRequestId}}/status
Authorization: Bearer {{$auth.token("consumer")}}
Content-Type: application/json

"IN_REVIEW"
