package ch.agridata.auditing.api;

/**
 * Defines the set of supported actions that can be recorded. It ensures standardized naming for audit events.
 *
 * @CommentLastReviewed 2026-01-22
 */

public enum ActionEnum {
  CONSENT_REQUEST_REOPENED,
  CONSENT_REQUEST_GRANTED,
  CONSENT_REQUEST_DECLINED,
  DATA_REQUEST_SUBMITTED,
  DATA_REQUEST_REJECTED,
  DATA_REQUEST_APPROVED,
  DATA_REQUEST_ACTIVATED,
  DATA_REQUEST_WITHDRAWN,
  CONSENT_REQUEST_TERMINATED,

  // consumer
  CONTRACT_INDIVIDUAL_SIGNATURE_FOR_CONSUMER_CHOSEN,
  CONTRACT_COLLECTIVE_SIGNATURE_FOR_CONSUMER_CHOSEN,
  CONTRACT_FIRST_CONSUMER_SLOT_SIGNED,
  CONTRACT_SECOND_CONSUMER_SLOT_SIGNED,
  DATA_REQUEST_RELEASED_BY_CONSUMER,

  // provider
  CONTRACT_INDIVIDUAL_SIGNATURE_FOR_PROVIDER_CHOSEN,
  CONTRACT_COLLECTIVE_SIGNATURE_FOR_PROVIDER_CHOSEN,
  CONTRACT_FIRST_PROVIDER_SLOT_SIGNED,
  CONTRACT_SECOND_PROVIDER_SLOT_SIGNED,
  DATA_REQUEST_RELEASED_BY_PROVIDER,

  CONTRACT_PDF_ELECTRONICALLY_SIGNED
}
