agridata:
  exception-handling:
    return-debug: true
  agreement:
    otp:
      validation:
        enabled: true
  aws:
    send-sms:
      enabled: true
bit:
  signature:
    key-bearer: "BLW-Agridata"
    profile: "BLW-Agridata-SR-hs"
quarkus:
  cache:
    caffeine:
      agis-api-register:
        expire-after-write: 5M
        maximum-size: 100
      tvd-api-fetch-equid-owner-legal-units:
        expire-after-write: 5M
        maximum-size: 100
      uid-register:
        expire-after-write: 5M
        maximum-size: 100
  application:
    name: agridata.ch
  banner:
    path: banner.txt
  cxf:
    client:
      uid:
        client-endpoint-url: https://www.uid-wse-a.admin.ch/V5.0/PublicServices.svc
        service-interface: ch.admin.uid.xmlns.uid_wse.IPublicServices
        wsdl: classpath:wsdl/uid-register.wsdl
    codegen:
      wsdl2java:
        uid:
          includes: wsdl/uid-register.wsdl
  datasource:
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    migrate-at-start: true
  hibernate-orm:
    mapping:
      format:
        global: ignore # See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26#jackson-based-json-serialization
  http:
    auth:
      permission:
        api-protected:
          paths: /api/*
          policy: authenticated
        unprotected:
          paths: /q/*
          policy: permit
          auth-mechanism: none
    cors:
      access-control-allow-credentials: true
      enabled: true
      headers:
        - Authorization
        - Content-Type
        - X-Impersonated-AgateLoginId
      methods:
        - GET
        - PUT
        - POST
        - DELETE
        - OPTIONS
        - PATCH
    port: 8060
  micrometer:
    enabled: true
    binder:
      jvm: true
      system: true
      http-server:
        enabled: true

  log:
    category:
      "ch.agridata.common.filters":
        min-level: TRACE
      "ch.agridata.common.filters.RestClientLoggingFilter":
        min-level: TRACE
    console:
      json:
        enabled: true
        pretty-print: false
      format: >-
        %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %s [%c] (%t) requestId: %X{requestId}, userId: %X{agateUserId},  api: %X{api}%e%n
  oidc:
    authentication:
      pkce-required: true
      user-info-required: true
  oidc-client:
    agis-api:
      grant:
        type: CLIENT
      refresh-token-time-skew: 1M # Refreshs the token one minute before it expires to avoid timing issues
    tvd-api:
      grant:
        type: CLIENT
      refresh-token-time-skew: 1M # Refreshs the token one minute before it expires to avoid timing issues
    acontrol-api:
      grant:
        type: CLIENT
      refresh-token-time-skew: 1M # Refreshs the token one minute before it expires to avoid timing issues
  rest-client:
    agis-api:
      key-store-type: PKCS12
    bit-signature-api:
      key-store-type: PKCS12
      trust-store-type: PKCS12
      read-timeout: 120000
    acontrol-api:
      key-store-type: PKCS12
  s3:
    aws:
      region: eu-central-2
      credentials:
        type: default
  ses:
    aws:
      region: eu-central-2
      credentials:
        type: default
  sns:
    aws:
      region: eu-central-2
      credentials:
        type: default
  smallrye-openapi:
    info-description: "This API provides access to the agridata.ch data exchange platform, enabling Users
    to discover, request, approve, and manage data sharing agreements.\n\n
    - **For Data Consumers**: Select this API subset to view only the endpoints relevant to you: [Data Consumer](/q/swagger-ui/?urls.primaryName=Data+Consumer)\n
    - **For Data Providers**: Select this API subset to view only the endpoints relevant to you: [Data Providers](/q/swagger-ui/?urls.primaryName=Data+Provider)"
    info-title: agridata.ch API
    store-schema-directory: target/openapi
    store-schema-file-name: agridata-api
  swagger-ui:
    theme: material
    always-include: true
    oauth-scopes: openid offline_access
    oauth-use-pkce-with-authorization-code-grant: true
    enabled: true
    urls:
      All: /q/openapi
      agridata.ch Web App: /q/openapi/subsets/agridata.ch%20Web%20App
      agridata.ch Mobile App: /q/openapi/subsets/Mobile%20App
      Data Consumer: /q/openapi/subsets/Data%20Consumer
      Data Provider: /q/openapi/subsets/Data%20Provider
    urls-primary-name: All
    default-models-expand-depth: -1
mp:
  openapi:
    scan:
      exclude:
        packages:
          - org.openapitools.api # excludes the automatically generated apis (e.g. AGIS) from the openapi documents
        classes:
          - ch.agridata.common.openapi.OpenApiSubsetController
