-- ===============================================
-- data_source_system
-- ===============================================
INSERT INTO public.data_source_system (id, archived, created_by, created_at, modified_by, modified_at, data_provider_id, code, name)
VALUES
('e93f1023-850d-4188-bf40-50e5eedaaa57', false, null, NOW(), null, NOW(), 'e37b148b-9a0f-4c2e-80c5-fe9c9416b640', 'ZO_API', '{"de": "ZO-API", "fr": "ZO-API", "it": "ZO-API"}')
ON CONFLICT (id) DO UPDATE SET archived = EXCLUDED.archived, modified_by = EXCLUDED.modified_by, modified_at = EXCLUDED.modified_at, data_provider_id = EXCLUDED.data_provider_id, code = EXCLUDED.code, name = EXCLUDED.name;

-- ===============================================
-- data_products
-- ===============================================
INSERT INTO data_product (
    id,
    archived,
    created_at,
    modified_at,
    data_source_system_id,
    name,
    description,
    rest_client_identifier_code,
    rest_client_method_code,
    rest_client_path_template,
    rest_client_request_template,
    flow_code,
    deprecated_since
)
VALUES (
--  TVD (ANIMAL TRACING)
    '6319423c-e4fc-4a47-be6e-43888f58f94f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Rinderdetail', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Rinderdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Nachkommen, Meldungen und Aufenthalten geliefert.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/cattle/{{eartagNumber}}?dataPackage=TVD_CattleDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'c4d3b0a3-b486-40b8-a324-5029034433cc'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Rinderbestand', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Rinderbestand für eine spezifische TVD-Nummer/BUR-Nummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/cattle/livestock?dataPackage=TVD_CattleLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '3e0bfd53-94c7-4a73-8d71-0f2c64313c3f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equidendetail Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Equidendaten für eine spezifische UELN. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Eigentümer, Eltern, Aufenthalten, Signalement, Nachkommen und Passdaten geliefert. Das Datenpaket ist den Equiden Zuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/equids/{{ueln}}?dataPackage=TVD_EquidDetailBreedingV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '593913ac-0294-431b-adf3-5227ff8fddff'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equidendetail', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Equidendaten für eine spezifische UELN. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Eigentümer, Eltern, Aufenthalten, Signalement und Nachkommen geliefert.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/equids/{{ueln}}?dataPackage=TVD_EquidDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '298b653c-b326-40d3-a3d1-97e2e9d9ca22'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equiden Eigentumsliste', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Equiden Eigentumsliste eines Eigentümers. Es umfasst die Equidenliste mit den Basisinformationen der Tiere. Zusätzlich werden Angaben zu Eigentümer, Eigentümer Adresse und Standort der Tiere geliefert.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/legalunits/{{uid}}/ownership?dataPackage=TVD_EquidOwnershipListV1&recipientUid={{recipientUid}}',
    NULL,
    'UID_BASED_POST_VALIDATION',
    NULL),
    (
    'e08af9d2-99ec-41b3-a77c-d4457415944f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Tierhaltungsdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält Tierhaltungsdaten für eine spezifische TVD-Nummer / BUR-Nummer. Es umfasst Adresse und andere betriebsspezifische Daten der Tierhaltung.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/customer/shared-data/localunits/{{bur}}?dataPackage=TVD_FarmDataV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    'b17ae68a-42a8-47fe-ba7b-ec7105c5c5c7'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Bewirtschafterdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Bewirtschafter für eine spezifische TVD-Nummer / BUR-Nummer. Es umfasst Daten der Rechtspersönlichkeit (natürliche oder juristische Person) sowie deren Kontaktdaten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/customer/shared-data/localunits/{{bur}}/legalunit?dataPackage=TVD_FarmManagerV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '5da9e6e0-4c17-4683-af89-b49206472ae7'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Ziegendetail', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Ziegendaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Nachkom-men, Meldungen und Aufenthalten geliefert.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/goats/{{eartagNumber}}?dataPackage=TVD_GoatDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '5aa2ee15-4f66-46ed-aaf2-55e6db55f960'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Ziegenbestand', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Ziegenbestand für eine spezifische TVD-Nummer/BURNummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/goats/livestock?dataPackage=TVD_GoatLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '7e4b1b3e-bcfb-4d94-923d-1277828de70b'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Schafdetail', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Schafdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Nachkommen, Meldungen und Aufenthalten geliefert.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/sheep/{{eartagNumber}}?dataPackage=TVD_SheepDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'c6f18e45-95f8-47b3-9b11-9cbae351a9b2'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Schafbestand', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Schafbestand für eine spezifische TVD-Nummer/BUR-Nummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/sheep/livestock?dataPackage=TVD_SheepLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
--  ZO-API
    (
    '2f28d2ec-8797-46fd-8149-9c70ac5f2ebe'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbewegungsdaten Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Rindern innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht, Missbildungen und Meldungen.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_CattleDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '0b42afb7-3683-4065-9cb3-396995a5be97'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderdetail Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Rinderdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Nachkommen, Missbildungen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinder Zuchtorganisationen vorenthalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/{{eartagNumber}}?dataPackage=ZOAPI_CattleDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'd10b898f-9796-4993-9654-8f092b97989d'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbestand Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Rinderbestand für eine spezifische TVD-Nr/BUR-Nr. Es umfasst den aktuellen Bestand und Stammbetrieb sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Missbildungen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinder Zuchtorganisationen vorenthalten', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/livestock?dataPackage=ZOAPI_CattleLivestockV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '59115547-cfd5-428a-9863-6cd1b2200013'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Tierhaltungsdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält Tierhaltungsdaten für eine spezifische TVD-Nr / BUR-Nr. Es umfasst Adresse und und andere betriebsspezifische Daten der Tierhaltung.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'tbd',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    'ec5b9f05-0b8d-4833-9447-d7338fe1dc78'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Bewirtschafterdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Bewirtschafter für eine spezifische TVD-Nr / BUR-Nr. Es umfasst personenbezogene Daten des Bewirtschafters.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'tbd',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL)
ON CONFLICT (id) DO UPDATE
SET
    archived = EXCLUDED.archived,
    created_at = EXCLUDED.created_at,
    modified_at = EXCLUDED.modified_at,
    data_source_system_id = EXCLUDED.data_source_system_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    rest_client_identifier_code = EXCLUDED.rest_client_identifier_code,
    rest_client_method_code = EXCLUDED.rest_client_method_code,
    rest_client_path_template = EXCLUDED.rest_client_path_template,
    rest_client_request_template = EXCLUDED.rest_client_request_template,
    flow_code = EXCLUDED.flow_code,
    deprecated_since = EXCLUDED.deprecated_since;
