ALTER TABLE data_request
    DROP COLUMN data_consumer_uid;

ALTER TABLE data_product
    DROP COLUMN data_provider_id;

INSERT INTO data_product (
    id, archived, created_at, modified_at,
    data_source_system_code, name, description
) VALUES
(     'c661ea48-106d-4d7a-a5d1-a9a6db48dd8c'::uuid,     false,     NOW() - INTERVAL '19 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'R01', 'fr', 'R01', 'it', 'R01'),     jsonb_build_object('de', 'Datensatz über Nutztiere auf mittleren Höfen.', 'fr', 'Données sur les animaux d’élevage dans les exploitations moyennes.', 'it', 'Dati sul bestiame negli allevamenti di medie dimensioni.')   ),
(     '147e8c40-78cc-4db3-a909-65504aa62a64'::uuid,     false,     NOW() - INTERVAL '19 days',     NOW() - INTERVAL '9 days',          'AGIS',     jsonb_build_object('de', 'R02', 'fr', 'R02', 'it', 'R02'),     jsonb_build_object('de', 'Informationen über den Anbau von Winterweizen.', 'fr', 'Informations sur la culture du blé d’hiver.', 'it', 'Informazioni sulla coltivazione del grano invernale.')   ),
(     '254bb1f1-05d3-4c4e-80ea-2fa075771ed7'::uuid,     false,     NOW() - INTERVAL '14 days',     NOW() - INTERVAL '7 days',          'AGIS',     jsonb_build_object('de', 'R03', 'fr', 'R03', 'it', 'R03'),     jsonb_build_object('de', 'Statistiken zu Milchviehbetrieben im Kanton Bern.', 'fr', 'Statistiques sur les exploitations laitières dans le canton de Berne.', 'it', 'Statistiche sugli allevamenti da latte nel cantone di Berna.')   ),
(     '085e4b72-964d-4bd5-a3c9-224d8c5585af'::uuid,     false,     NOW() - INTERVAL '18 days',     NOW() - INTERVAL '4 days',          'AGIS',     jsonb_build_object('de', 'S01', 'fr', 'S01', 'it', 'S01'),     jsonb_build_object('de', 'Erhebung zu Obstplantagen und Baumarten.', 'fr', 'Enquête sur les vergers et les types d’arbres.', 'it', 'Indagine sui frutteti e le specie arboree.')   ),
(     'a795d0b0-f177-4bb4-8e41-1ed12d358c79'::uuid,     false,     NOW() - INTERVAL '15 days',     NOW() - INTERVAL '6 days',          'AGIS',     jsonb_build_object('de', 'S02', 'fr', 'S02', 'it', 'S02'),     jsonb_build_object('de', 'Analyse zu Gemüseanbau in Gewächshäusern.', 'fr', 'Analyse de la culture des légumes sous serre.', 'it', 'Analisi della coltivazione di ortaggi in serra.')   ),
(     '0a808700-d89e-4fa0-a2b8-8edb15f3addd'::uuid,     false,     NOW() - INTERVAL '15 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'S03', 'fr', 'S03', 'it', 'S03'),     jsonb_build_object('de', 'Überblick über Biohöfe und ihre Erträge.', 'fr', 'Aperçu des fermes biologiques et de leurs rendements.', 'it', 'Panoramica delle aziende biologiche e delle loro rese.')   ),
(     'ef4f42dd-eaa9-4af1-988c-86b47bd963fe'::uuid,     false,     NOW() - INTERVAL '11 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'S04', 'fr', 'S04', 'it', 'S04'),     jsonb_build_object('de', 'Erfassung der Bodenqualität landwirtschaftlicher Flächen.', 'fr', 'Évaluation de la qualité des sols des terres agricoles.', 'it', 'Valutazione della qualità del suolo dei terreni agricoli.')   ),
(     '2375219c-5fe3-458f-bd07-d3c2c87e2539'::uuid,     false,     NOW() - INTERVAL '18 days',     NOW() - INTERVAL '9 days',          'AGIS',     jsonb_build_object('de', 'S05', 'fr', 'S05', 'it', 'S05'),     jsonb_build_object('de', 'Bericht über den Einsatz von Pflanzenschutzmitteln.', 'fr', 'Rapport sur l''utilisation des produits phytosanitaires.', 'it', 'Rapporto sull''uso dei fitofarmaci.')   ),
(     '64e39df0-2e56-4204-9c44-a43e1e26a2e8'::uuid,     false,     NOW() - INTERVAL '12 days',     NOW() - INTERVAL '9 days',          'AGIS',     jsonb_build_object('de', 'S06', 'fr', 'S06', 'it', 'S06'),     jsonb_build_object('de', 'Verzeichnis von Weideflächen in alpinen Regionen.', 'fr', 'Répertoire des pâturages en régions alpines.', 'it', 'Elenco dei pascoli nelle regioni alpine.')   ),
(     '1dad9f91-30d8-45c9-8c82-ad72f4cb22e7'::uuid,     false,     NOW() - INTERVAL '14 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'S07', 'fr', 'S07', 'it', 'S07'),     jsonb_build_object('de', 'Zahlen zur Schweinezucht in der Ostschweiz.', 'fr', 'Chiffres sur l’élevage porcin en Suisse orientale.', 'it', 'Dati sull’allevamento di suini nella Svizzera orientale.')   ),
(     '695ca7e2-aaf1-4e87-a590-1b741962eef7'::uuid,     false,     NOW() - INTERVAL '17 days',     NOW() - INTERVAL '5 days',          'AGIS',     jsonb_build_object('de', 'S01_Prov', 'fr', 'S01_Prov', 'it', 'S01_Prov'),     jsonb_build_object('de', 'Provisorische Daten über Kartoffelanbau.', 'fr', 'Données provisoires sur la culture des pommes de terre.', 'it', 'Dati provvisori sulla coltivazione delle patate.')   ),
(     'a790ab37-6863-48fd-b387-f51448ecd04f'::uuid,     false,     NOW() - INTERVAL '11 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'S02_Prov', 'fr', 'S02_Prov', 'it', 'S02_Prov'),     jsonb_build_object('de', 'Provisorische Analyse zum Weinbau in der Romandie.', 'fr', 'Analyse provisoire de la viticulture en Romandie.', 'it', 'Analisi provvisoria della viticoltura in Romandia.')   ),
(     'c760b5e4-f176-4c42-a42b-928bb4bc514d'::uuid,     false,     NOW() - INTERVAL '18 days',     NOW() - INTERVAL '3 days',          'AGIS',     jsonb_build_object('de', 'S03_Prov', 'fr', 'S03_Prov', 'it', 'S03_Prov'),     jsonb_build_object('de', 'Vorläufige Studie zu Hofgrößen im Mittelland.', 'fr', 'Étude préliminaire sur la taille des fermes au Plateau suisse.', 'it', 'Studio preliminare sulla dimensione delle aziende nel Mittelland.')   ),
(     '99451e02-0c43-480e-9647-c19c29fb899d'::uuid,     false,     NOW() - INTERVAL '13 days',     NOW() - INTERVAL '6 days',          'AGIS',     jsonb_build_object('de', 'S04_Prov', 'fr', 'S04_Prov', 'it', 'S04_Prov'),     jsonb_build_object('de', 'Erste Ergebnisse zum Anbau von Raps.', 'fr', 'Premiers résultats sur la culture du colza.', 'it', 'Primi risultati sulla coltivazione della colza.')   ),
(     'e362b474-b114-4edf-a7db-0fbcd1436414'::uuid,     false,     NOW() - INTERVAL '12 days',     NOW() - INTERVAL '5 days',          'AGIS',     jsonb_build_object('de', 'S05_Prov', 'fr', 'S05_Prov', 'it', 'S05_Prov'),     jsonb_build_object('de', 'Pilotdaten über Wasserverbrauch auf Feldern.', 'fr', 'Données pilotes sur la consommation d’eau dans les champs.', 'it', 'Dati pilota sul consumo d’acqua nei campi.')   ),
(     'f64cbcd6-4e3f-4eed-9087-2fec0a40a772'::uuid,     false,     NOW() - INTERVAL '18 days',     NOW() - INTERVAL '6 days',          'AGIS',     jsonb_build_object('de', 'S06_Prov', 'fr', 'S06_Prov', 'it', 'S06_Prov'),     jsonb_build_object('de', 'Testdatensatz zu Maisproduktion.', 'fr', 'Jeu de données test sur la production de maïs.', 'it', 'Set di dati di test sulla produzione di mais.')   ),
(     '94055564-7457-481f-8cf8-a0f39f22b250'::uuid,     false,     NOW() - INTERVAL '16 days',     NOW() - INTERVAL '6 days',          'AGIS',     jsonb_build_object('de', 'S07_Prov', 'fr', 'S07_Prov', 'it', 'S07_Prov'),     jsonb_build_object('de', 'Erhebung zu Treibhausemissionen in der Landwirtschaft.', 'fr', 'Enquête sur les émissions de gaz à effet de serre dans l’agriculture.', 'it', 'Indagine sulle emissioni di gas serra in agricoltura.')   ),
(     '46f8a883-da7c-49b3-b986-10a24b1e09ef'::uuid,     false,     NOW() - INTERVAL '10 days',     NOW() - INTERVAL '7 days',          'AGIS',     jsonb_build_object('de', 'A01', 'fr', 'A01', 'it', 'A01'),     jsonb_build_object('de', 'Datenpaket zur Futterproduktion.', 'fr', 'Ensemble de données sur la production de fourrage.', 'it', 'Pacchetto di dati sulla produzione di foraggi.')   ),
(     'da999291-961c-484d-a1fa-00f6099f8b3b'::uuid,     false,     NOW() - INTERVAL '16 days',     NOW() - INTERVAL '8 days',          'AGIS',     jsonb_build_object('de', 'A01_Prov', 'fr', 'A01_Prov', 'it', 'A01_Prov'),     jsonb_build_object('de', 'Vorabinformation über Agrarsubventionen.', 'fr', 'Information préliminaire sur les subventions agricoles.', 'it', 'Informazioni preliminari sui sussidi agricoli.')   );
