-- ===============================================
-- data_products
-- ===============================================
DELETE FROM data_request_data_product
WHERE data_product_id = 'ec5b9f05-0b8d-4833-9447-d7338fe1dc78'; -- ZO API: Bewirtschafterdaten

DELETE FROM data_product
WHERE id = 'ec5b9f05-0b8d-4833-9447-d7338fe1dc78'; -- ZO API: Bewirtschafterdaten

INSERT INTO data_product (
    id,
    archived,
    created_at,
    modified_at,
    data_source_system_id,
    name,
    description,
    rest_client_identifier_code,
    rest_client_method_code,
    rest_client_path_template,
    rest_client_request_template,
    flow_code,
    deprecated_since
)
VALUES (
--  TVD (ANIMAL TRACING)
    '6319423c-e4fc-4a47-be6e-43888f58f94f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Rinderdetail', 'fr', 'Informations sur les bovins', 'it', 'Dettagli dei bovini'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Rinderdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Nachkommen, Meldungen und Aufenthalten geliefert.',
        'fr', 'Ce paquet de données contient les informations relatives aux bovins pour une marque auriculaire spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur la localisation, les parents, les maladies, les descendants, les notifications et les séjours sont également fournies.',
        'it', 'Questo pacchetto di dati contiene i dati relativi ai bovini per una marca auricolare specifica. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su località, parenti, malattie, discendenti, notifiche e soggiorni.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/cattle/{{eartagNumber}}?dataPackage=TVD_CattleDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'c4d3b0a3-b486-40b8-a324-5029034433cc'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Rinderbestand', 'fr', 'Cheptel bovin', 'it', 'Effettivo di bovini'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Rinderbestand für eine spezifische TVD-Nummer/BUR-Nummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.',
        'fr', 'Ce paquet de données contient des informations relatives au cheptel bovin actuel pour un numéro de numéro BDTA/REE spécifique. Il comprend la liste actualisée du cheptel ainsi que certaines informations de base sur les animaux.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di bovini per un numero BDTA/numero RIS specifico. Comprende l’elenco aggiornato degli animali e alcune informazioni di base sugli animali.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/cattle/livestock?dataPackage=TVD_CattleLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '3e0bfd53-94c7-4a73-8d71-0f2c64313c3f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equidendetail Zucht', 'fr', 'Informations sur les équidés - élevage', 'it', 'Dettagli degli equidi dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Equidendaten für eine spezifische UELN. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Eigentümer, Eltern, Aufenthalten, Signalement, Nachkommen und Passdaten geliefert. Das Datenpaket ist den Equiden Zuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux équidés pour un UELN spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur les propriétaires, les parents, les séjours, les signalements, les descendants et les données du passeport sont également fournies. Ce paquet de données est réservé aux organisations d’élevage d’équidés.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli equidi per un numero UELN specifico. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su proprietari, parenti, soggiorni, segnalamenti, discendenti e dati del passaporto. Il pacchetto di dati è riservato alle organizzazioni d’allevamento degli equidi.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/equids/{{ueln}}?dataPackage=TVD_EquidDetailBreedingV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '593913ac-0294-431b-adf3-5227ff8fddff'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equidendetail', 'fr', 'Informations sur les équidés', 'it', 'Dettagli degli equidi'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Equidendaten für eine spezifische UELN. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Eigentümer, Eltern, Aufenthalten, Signalement und Nachkommen geliefert.',
        'fr', 'Ce paquet de données contient les informations relatives aux équidés pour un UELN spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur les propriétaires, les parents, les séjours, les signalements et les descendants sont également fournies.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli equidi per un numero UELN specifico. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su proprietari, parenti, soggiorni, segnalamenti e discendenti.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/equids/{{ueln}}?dataPackage=TVD_EquidDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '298b653c-b326-40d3-a3d1-97e2e9d9ca22'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Equiden Eigentumsliste', 'fr', 'Liste des équidés d’un propriétaire', 'it', 'Elenco degli equidi di proprietà'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Equiden Eigentumsliste eines Eigentümers. Es umfasst die Equidenliste mit den Basisinformationen der Tiere. Zusätzlich werden Angaben zu Eigentümer, Eigentümer Adresse und Standort der Tiere geliefert.',
        'fr', 'Ce paquet de données contient la liste des équidés d’un propriétaire. Il comprend la liste des équidés et les informations de base relatives aux animaux. Des informations sur les propriétaires, leur adresse et la localisation des animaux sont également fournies.',
        'it', 'Questo pacchetto di dati contiene l’elenco degli equidi di proprietà di un proprietario. Comprende l’elenco degli equidi con le informazioni di base degli animali. Vengono inoltre fornite informazioni su proprietario, indirizzo del proprietario e attuale località degli animali.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/equid/shared-data/legalunits/{{uid}}/ownership?dataPackage=TVD_EquidOwnershipListV1&recipientUid={{recipientUid}}',
    NULL,
    'UID_BASED_POST_VALIDATION',
    NULL),
    (
    'e08af9d2-99ec-41b3-a77c-d4457415944f'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Tierhaltungsdaten', 'fr', 'Données relatives à l’élevage', 'it', 'Dati sull’azienda'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält Tierhaltungsdaten für eine spezifische TVD-Nummer / BUR-Nummer. Es umfasst Adresse und andere betriebsspezifische Daten der Tierhaltung.',
        'fr', 'Ce paquet de données contient des informations relatives à l’élevage pour un numéro BDTA/REE spécifique. Il comprend l’adresse et d’autres informations spécifiques à l’exploitation relatives à l’élevage.',
        'it', 'Questo pacchetto di dati contiene i dati relativi all’azienda per un numero BDTA/numero RIS specifico. Comprende l’indirizzo e altri dati specifici dell’azienda.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/customer/shared-data/localunits/{{bur}}?dataPackage=TVD_FarmDataV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    'b17ae68a-42a8-47fe-ba7b-ec7105c5c5c7'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Bewirtschafterdaten', 'fr', 'Données relatives à l’exploitant', 'it', 'Dati sull’allevatore'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Bewirtschafter für eine spezifische TVD-Nummer / BUR-Nummer. Es umfasst Daten der Rechtspersönlichkeit (natürliche oder juristische Person) sowie deren Kontaktdaten.',
        'fr', 'Ce paquet de données contient les informations relatives à l’exploitant actuel pour un numéro BDTA/REE spécifique. Il comprend les données relatives à la personnalité juridique (personne physique ou morale) ainsi que ses coordonnées.',
        'it', 'Questo pacchetto di dati contiene l’allevatore attuale per un numero BDTA/numero RIS specifico. Comprende i dati relativi alla personalità giuridica (persona fisica o giuridica) e i relativi recapiti.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/customer/shared-data/localunits/{{bur}}/legalunit?dataPackage=TVD_FarmManagerV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '5da9e6e0-4c17-4683-af89-b49206472ae7'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Ziegendetail', 'fr', 'Informations sur les chèvres', 'it', 'Dettagli delle capre'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Ziegendaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Nachkommen, Meldungen und Aufenthalten geliefert.',
        'fr', 'Ce paquet de données contient les informations relatives aux chèvres pour une marque auriculaire spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur la localisation, les parents, les descendants, les notifications et les séjours sont également fournies.',
        'it', 'Questo pacchetto di dati contiene i dati relativi alle capre per una marca auricolare specifica. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su località, parenti, discendenti, notifiche e soggiorni.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/goats/{{eartagNumber}}?dataPackage=TVD_GoatDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '5aa2ee15-4f66-46ed-aaf2-55e6db55f960'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Ziegenbestand', 'fr', 'Cheptel de chèvres', 'it', 'Effettivo di capre'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Ziegenbestand für eine spezifische TVD-Nummer/BUR-Nummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.',
        'fr', 'Ce paquet de données contient les informations relatives au cheptel de chèvres actuel pour un numéro de numéro BDTA/REE spécifique. Il comprend la liste actualisée du cheptel ainsi que certaines informations de base sur les animaux.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di capre per un numero BDTA/numero RIS specifico. Comprende l’elenco aggiornato degli animali e alcune informazioni di base sugli animali.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/goats/livestock?dataPackage=TVD_GoatLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '7e4b1b3e-bcfb-4d94-923d-1277828de70b'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Schafdetail', 'fr', 'Informations sur les ovins', 'it', 'Dettagli degli ovini'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Schafdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Nachkommen, Meldungen und Aufenthalten geliefert.',
        'fr', 'Ce paquet de données contient les informations relatives aux ovins pour une marque auriculaire spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur la localisation, les parents, les descendants, les notifications et les séjours sont également fournies.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli ovini per una marca auricolare specifica. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su località, parenti, discendenti, notifiche e soggiorni.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/sheep/{{eartagNumber}}?dataPackage=TVD_SheepDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'c6f18e45-95f8-47b3-9b11-9cbae351a9b2'::uuid,
    false,
    NOW(),
    NOW(),
    '4ccbfa06-a547-4a76-9dfc-61c22a4ea8ce',
    jsonb_build_object('de', 'Schafbestand', 'fr', 'Cheptel ovin', 'it', 'Effettivo di ovini'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Schafbestand für eine spezifische TVD-Nummer/BUR-Nummer. Es umfasst die aktuelle Bestandesliste sowie einige Basisinformationen der Tiere.',
        'fr', 'Ce paquet de données contient les informations relatives au cheptel ovin actuel pour un numéro BDTA/REE spécifique. Il comprend la liste actualisée du cheptel ainsi que certaines informations de base sur les animaux.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di ovini per un numero BDTA/numero RIS specifico. Comprende l’elenco aggiornato degli animali e alcune informazioni di base sugli animali.'),
    'TVD_ANIMAL_TRACING_API',
    'GET',
    'v1.0/animal/shared-data/sheep/livestock?dataPackage=TVD_SheepLivestockV1&localUnitNumber={{bur}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
--  ZO-API
    (
    '2f28d2ec-8797-46fd-8149-9c70ac5f2ebe'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbewegungsdaten Zucht', 'fr', 'Données sur les déplacements des bovins - élevage', 'it', 'Dati sugli spostamenti dei bovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Rindern innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht, Missbildungen und Meldungen. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux déplacements des bovins affectés à une OE au cours d’une période définie (de – à). Il contient des informations de base actualisées, ainsi que des informations sur la localisation, les parents, l’élevage, les malformations et les notifications. Ce paquet de données est réservé aux organisations d’élevage bovin.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli spostamenti dei bovini assegnati all’organizzazione d’allevamento in un periodo di tempo definito (da – a). Comprende informazioni di base aggiornate, nonché informazioni su località, parenti, allevamento, malformazioni e notifiche. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di bovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_CattleDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '0b42afb7-3683-4065-9cb3-396995a5be97'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderdetail Zucht', 'fr', 'Informations sur les bovins - élevage', 'it', 'Dettagli dei bovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Rinderdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Nachkommen, Missbildungen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux bovins pour une marque auriculaire spécifique. Il comprend les informations de base sur l’animal recherché. Des informations sur la localisation, les parents, les maladies, l’élevage, les descendants, les malformations, les notifications, les séjours et l’historique de l’exploitation d’origine sont également fournies. Ce paquet de données est réservé aux organisations d’élevage bovin.',
        'it', 'Questo pacchetto di dati contiene i dati relativi ai bovini per una marca auricolare specifica. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su località, parenti, malattie, allevamento, discendenti, malformazioni, notifiche, soggiorni e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di bovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/{{eartagNumber}}?dataPackage=ZOAPI_CattleDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'd10b898f-9796-4993-9654-8f092b97989d'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbestand Zucht', 'fr', 'Cheptel bovin - élevage', 'it', 'Effettivo di bovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Rinderbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Missbildungen, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données comprend des informations sur le cheptel bovin actuel pour un REE spécifique. Il contient le cheptel et les informations de base relatives aux animaux. Des informations sur la localisation, les parents, les maladies, l’élevage, les malformations, les notifications et l’historique de l’exploitation d’origine sont également fournies. Ce paquet de données est réservé aux organisations d’élevage bovin.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di bovini per un numero RIS specifico. Comprende l’effettivo e le informazioni di base relative agli animali. Vengono inoltre fornite informazioni su località, parenti, malattie, allevamento, malformazioni, notifiche e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di bovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/livestock?dataPackage=ZOAPI_CattleLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '59115547-cfd5-428a-9863-6cd1b2200013'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Tierhaltungsdaten', 'fr', 'Données relatives à l’élevage', 'it', 'Dati sull’azienda'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält Tierhaltungsdaten für eine spezifische BUR-Nr. Es umfasst die Adresse und andere betriebsspezifische Daten der Tierhaltung.',
        'fr', 'Ce paquet de données contient les informations relatives à l’élevage pour un REE spécifique. Il comprend l’adresse et d’autres informations spécifiques à l’exploitation relatives à l’élevage.',
        'it', 'Questo pacchetto di dati contiene i dati relativi all’azienda per un numero RIS specifico. Comprende l’indirizzo e altri dati specifici dell’azienda.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/localunits/{{bur}}?dataPackage=ZOAPI_FarmDataV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '88dcf0f9-8502-4596-b035-45c5d548d262'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegenbewegungsdaten Zucht', 'fr', 'Données sur les déplacements des chèvres - élevage', 'it', 'Dati sugli spostamenti delle capre dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Ziegen innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht und Meldungen. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux déplacements des chèvres affectées à une OE au cours d’une période définie (de – à). Il contient des informations de base actualisées, ainsi que des informations sur la localisation, les parents, l’élevage et les notifications. Ce paquet de données est réservé aux organisations d’élevage de chèvres.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli spostamenti delle capre assegnate all’organizzazione d’allevamento in un periodo di tempo definito (da – a). Comprende informazioni di base aggiornate, nonché informazioni su località, parenti, allevamento e notifiche. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di capre.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_GoatDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '54decb00-cecd-4c64-b368-8ab999130ac4'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegendetail Zucht', 'fr', 'Informations sur les chèvres - élevage', 'it', 'Dettagli delle capre dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Ziegendaten für eine spezifische Ohrmarke und umfasst die Basisinformationen des Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Nachkommen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux chèvres pour une marque auriculaire spécifique et comprend les informations de base sur l’animal. Des informations sur la localisation, les parents, l’élevage, les descendants, les notifications, les séjours et l’historique de l’exploitation d’origine sont également fournies. Ce paquet de données est réservé aux organisations d’élevage de chèvres.',
        'it', 'Questo pacchetto di dati contiene i dati relativi alle capre per una marca auricolare specifica e comprende le informazioni di base dell’animale. Vengono inoltre fornite informazioni su località, parenti, allevamento, discendenza, notifiche, soggiorni e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di capre.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat/{{eartagNumber}}?dataPackage=ZOAPI_GoatDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'd156f252-c8c0-49de-8541-149c35aada6c'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegenbestand Zucht', 'fr', 'Cheptel de chèvres - élevage', 'it', 'Effettivo di capre dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Ziegenbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données comprend des informations relatives au cheptel de chèvres actuel pour un REE spécifique. Il comprend le cheptel ainsi que les informations de base relatives aux animaux. Des informations sur la localisation, les parents, l’élevage, les notifications et l’historique de l’exploitation d’origine sont également fournies. Ce paquet de données est réservé aux organisations d’élevage de chèvres.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di capre per un numero RIS specifico. Comprende l’effettivo e le informazioni di base degli animali. Vengono inoltre fornite informazioni su località, parenti, allevamento, notifiche e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di capre.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat/livestock?dataPackage=ZOAPI_GoatLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '720aa209-7aa8-4faf-8b1a-013a041084f2'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafbewegungsdaten Zucht', 'fr', 'Données relatives aux déplacements des ovins - élevage', 'it', 'Dati sugli spostamenti degli ovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Schafen innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht und Meldungen. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux déplacements des ovins affectés à une OE au cours d’une période définie (de – à). Il contient des informations de base actualisées, ainsi que des informations sur la localisation, les parents, l’élevage et les notifications. Ce paquet de données est réservé aux organisations d’élevage ovin.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli spostamenti degli ovini assegnati all’organizzazione d’allevamento in un periodo di tempo definito (da – a). Comprende informazioni di base aggiornate, nonché informazioni su località, parenti, allevamento e notifiche. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di ovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_SheepDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'b0a4ff29-cac4-4413-b8fb-7ff61f4ff2ac'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafdetail Zucht', 'fr', 'Informations sur les ovins - élevage', 'it', 'Dettagli degli ovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält die Schafdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Nachkommen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données contient les informations relatives aux ovins pour une marque auriculaire spécifique. Il comprend les informations de base sur l’animal recherché. Des informations supplémentaires sont fournies sur la localisation, les parents, les maladies, l’élevage, les descendants, les notifications, les séjours et l’historique de l’exploitation d’origine. Ce paquet de données est réservé aux organisations d’élevage ovin.',
        'it', 'Questo pacchetto di dati contiene i dati relativi agli ovini per una marca auricolare specifica. Comprende le informazioni di base dell’animale consultato. Vengono inoltre fornite informazioni su località, parenti, malattie, allevamento, discendenti, notifiche, soggiorni e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di ovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep/{{eartagNumber}}?dataPackage=ZOAPI_SheepDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'e6128e10-5d2b-4096-8356-b6523cb30e92'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafbestand Zucht', 'fr', 'Cheptel ovin - élevage', 'it', 'Effettivo di ovini dell’allevamento'),
    jsonb_build_object(
        'de', 'Dieses Datenpaket enthält den aktuellen Schafbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.',
        'fr', 'Ce paquet de données comprend des informations relatives au cheptel ovin actuel pour un REE spécifique. Il comprend le cheptel ainsi que les informations de base relatives aux animaux. Des informations sur la localisation, les parents, l’élevage, les notifications et l’historique de l’exploitation d’origine sont également fournies. Ce paquet de données est réservé aux organisations d’élevage ovin.',
        'it', 'Questo pacchetto di dati contiene l’attuale effettivo di ovini per un numero RIS specifico. Comprende l’effettivo e le informazioni di base degli animali. Vengono inoltre fornite informazioni su località, parenti, allevamento, notifiche e la storia dell’azienda d’origine. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di ovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep/livestock?dataPackage=ZOAPI_SheepLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    'a26e6bb1-7f48-4064-adad-20e0c4966b08'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderschlachtdaten Zucht', 'fr', 'Données relatives à l’abattage de bovins - élevage', 'it', 'Dati sulla macellazione dei bovini dell’allevamento'),
    jsonb_build_object(
     'de', 'Dieses Datenpaket enthält die Schlachtdaten von Rindern innerhalb eines definierten Zeitraums (von–bis). Es umfasst Basisinformationen der Tiere sowie Angaben zu Standort, Eltern Zucht und Meldungen. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.',
     'fr', 'Ce paquet de données contient les informations relatives à l’abattage de bovins au cours d’une période définie (de – à). Il contient des informations de base sur les animaux, ainsi que des informations sur leur localisation, leurs parents, leur élevage et les notifications. Ce paquet de données est réservé aux organisations d’élevage bovin.',
     'it', 'Questo pacchetto di dati contiene i dati relativi alla macellazione dei bovini in un periodo di tempo definito (da – a). Comprende informazioni di base sugli animali, nonché informazioni su località,parenti, allevamento e notifiche. Il pacchetto di dati è riservato alle organizzazioni d’allevamento di bovini.'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/slaughter?dataPackage=ZOAPI_CattleSlaughterV1&dateFrom={{dateFrom}}&dateTo={{dateTo}}&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL)
ON CONFLICT (id) DO UPDATE
SET
    archived = EXCLUDED.archived,
    created_at = EXCLUDED.created_at,
    modified_at = EXCLUDED.modified_at,
    data_source_system_id = EXCLUDED.data_source_system_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    rest_client_identifier_code = EXCLUDED.rest_client_identifier_code,
    rest_client_method_code = EXCLUDED.rest_client_method_code,
    rest_client_path_template = EXCLUDED.rest_client_path_template,
    rest_client_request_template = EXCLUDED.rest_client_request_template,
    flow_code = EXCLUDED.flow_code,
    deprecated_since = EXCLUDED.deprecated_since;
