ALTER TABLE data_product
    DROP COLUMN data_source_product_id;

DELETE FROM data_product;

INSERT INTO data_product
            (id, archived, created_at, modified_at, data_source_system_code, name, description, rest_client_identifier_code, rest_client_method_code, rest_client_path, rest_client_request_template)
VALUES      ('c661ea48-106d-4d7a-a5d1-a9a6db48dd8c'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Person',
             'fr', 'Personne',
             'it', 'Persona'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält Angaben zur Person (Tierhalter und Bewirtschafter), wie: Name, Vorname, kantonale Personennummer, UID, Rechtsform, Postadresse, Telefon, Email und die Identifikationsnummer des dazugehörigen Betriebs.',
             'fr','Ce produit contient des informations personnelles sur les éleveurs et les exploitants, telles que : nom, prénom, numéro personnel cantonal, IDE, form juridique, adresse postale, téléphone et e-mail, ainsi que l’exploitation appartenant à la personne.',
             'it','Questo prodotto contiene informazioni concernenti la persona (detentori di animali e gestori): cognome, nome, numero personale cantonale, IDI, formagiuridica, indirizzo postale, telefono, e-mail e numero di identificazione dell''azienda corrispondente.'),
             'AGIS_REGISTER_V1',
             'POST',
             'register',
             '{"personSearchParameters":{"uid":"{{uid}}"}}'),
            ('147e8c40-78cc-4db3-a909-65504aa62a64'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Betrieb',
             'fr', 'Exploitation',
             'it', 'Azienda'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält Angaben zu Betrieben (von Tierhaltern und Bewirtschaftern), wie: kantonale Betriebsnummer, BUR Nummer, TVD-Nummer, Standortadresse, Koordinaten, Betriebsform.',
             'fr','Ce produit contient des informations générales sur les exploitations des éleveurs et exploitants, telles que : numéro d’identification cantonal de la forme d’exploitation, numéro REE, numéro BDTA, adresse du site, coordonnées, forme d’exploitation.',
             'it','Questo prodotto contiene informazioni generali concernenti le aziende (detentori di animali e gestori): ubicazione, coordinate, numeri aziendali.'),
             'AGIS_REGISTER_V1',
             'POST',
             'register',
             '{"farmSearchParameters":{"uid":"{{uid}}"}}'),
            ('085e4b72-964d-4bd5-a3c9-224d8c5585af'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Nutztiere auf Betrieb',
             'fr', 'Animaux de rente dans l’exploitation',
             'it', 'Animali da reddito nell’azienda'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Art und Anzahl Nutztiere, die auf einem Betrieb im Vorjahr gehalten wurden.',
             'fr','Ce produit contient l’espèce et le nombre d’animaux de rente qui sont détenus dans l’exploitation.',
             'it','Questo prodotto contiene informazioni sugli animali da reddito (specie e numero) detenuti dall’azienda.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["animalData"]},"dataRequestType":{"finalData":false}}'),
            ('a795d0b0-f177-4bb4-8e41-1ed12d358c79'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Nutztiere in Sömmerung',
             'fr', 'Animaux de rente en estivage',
             'it', 'Animali da reddito in estivazione'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Art und Anzahl Nutztiere pro Betrieb, die im Inland gesömmert wurden.',
             'fr','Ce produit contient l’espèce et le nombre d’animaux de rente qui ont été estivés dans le pays.',
             'it','Questo prodotto contiene informazioni sugli animali da reddito (specie e numero) per azienda estivati all’interno del Paese.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["animalSummeringData"]},"dataRequestType":{"finalData":false}}'),
            ('0a808700-d89e-4fa0-a2b8-8edb15f3addd'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Flächen Hauptkulturen',
             'fr', 'Surfaces de cultures principales',
             'it', 'Superfici delle colture principali'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Fläche der im entsprechenden Jahr angebauten Hauptkulturen eines Betriebs inklusive Angabe zur landwirtschaftlichen Zone, Standortgemeinde und der Produktionsform (z.B. Einsatz von Pflanzenschutzmitteln, Bio).',
             'fr','Ce produit contient la surface des cultures principales de l’année correspondante dans l’exploitation, y compris l’indication de la zone agricole, de la commune d’implantation et de la forme d’exploitation (utilisation de produits phytosanitaires, Bio).',
             'it','Questo prodotto contiene informazioni concernenti le superfici sulle quali nell’anno in questione sono state coltivate le colture principali di un’azienda, incluse le informazioni concernenti la zona agricola, il Comune di ubicazione e la forma di gestione (utilizzo di prodotti fitosanitari, bio).'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["generalSurfaceData"]},"dataRequestType":{"finalData":false}}'),
            ('ef4f42dd-eaa9-4af1-988c-86b47bd963fe'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Flächen Hanglagen',
             'fr', 'Surfaces en pente',
             'it', 'Superfici in zone declive'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält Flächen, die in einem Hang liegen mit einer Neigung grösser als 18%. Die Angaben sind aufgegliedert nach der Zone, Hauptkultur und Betrieb.',
             'fr','Ce produit contient des surfaces qui se situent dans une pente dont la déclivité est supérieure à 18%. Les données sont séparées selon la zone, la culture principale et l’exploitation.',
             'it','Questo prodotto contiene informazioni concernenti le superfici in zone con una declività superiore ai 18%. I dati sono suddivisi per zona, coltura principale e azienda.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["slopeSurfaceData"]},"dataRequestType":{"finalData":false}}'),
            ('2375219c-5fe3-458f-bd07-d3c2c87e2539'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Rebflächen Hanglagen',
             'fr', 'Surfaces viticoles en pente',
             'it', 'Vigneti in zone declive'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält Rebflächen, die in einem Hang liegen mit einer Neigung grösser als 30%. Die Angaben sind aufgegliedert nach der Zone, Hauptkultur und Betrieb.',
             'fr','Ce produit contient des surfaces viticoles qui se situent dans une pente dont la déclivité est supérieure à 30%. Les données sont séparées selon la zone, la culture principale et l’exploitation.',
             'it','Questo prodotto contiene informazioni sui vigneti con una declività superiore ai 30%. I dati sono suddivisi per zona, coltura principale e azienda.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["grapeSurfaceData"]},"dataRequestType":{"finalData":false}}'),
            ('64e39df0-2e56-4204-9c44-a43e1e26a2e8'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Biodiversitätsförderflächen',
             'fr', 'Surfaces de promotion de la biodiversité',
             'it', 'Superfici per la promozione della biodiversità'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Biodiversitätsförderflächen gemäss Direktzahlungsverordnung (DZV). Die Angaben sind aufgegliedert nach der Zone, Hauptkultur und Betrieb.',
             'fr','Ce produit contient les données sur les surfaces de promotion de la biodiversité selon l’ordonnance sur les paiements directs (OPD). Les données sont séparées selon la zone, la culture principale et l’exploitation.',
             'it','Questo prodotto contiene informazioni concernenti le superfici per la promozione della biodiversità in virtù dell’ordinanza sui pagamenti diretti (OPD). I dati sono suddivisi per zona, coltura principale e azienda.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["biodiversitySurfaceData"]},"dataRequestType":{"finalData":false}}'),
            ('1dad9f91-30d8-45c9-8c82-ad72f4cb22e7'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Vernetzungsflächen',
             'fr', 'Surfaces de mise en réseau',
             'it', 'Superfici per l’interconnessione'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Vernetzungsflächen gemäss Direktzahlungsverordnung (DZV). Die Angaben sind aufgegliedert nach der Zone, Hauptkultur und Betrieb.',
             'fr','Ce produit contient les données sur les surfaces de mise en réseau selon l’ordonnance sur les paiements directs (OPD). Les données sont séparées selon la zone, la culture principale et l’exploitation.',
             'it','Questo prodotto contiene informazioni concernenti le superfici di interconnessione in virtù dell’ordinanza sui pagamenti diretti (OPD). I dati sono suddivisi per zona, coltura principale e azienda.'),
             'AGIS_STRUCTURE_V1',
             'POST',
             'structure',
             '{"surveyYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataTypes":{"structureType":["networkSurfaceData"]},"dataRequestType":{"finalData":false}}'),
            ('46f8a883-da7c-49b3-b986-10a24b1e09ef'::uuid,
             false,
             Now(),
             Now(),
             'AGIS',
             Jsonb_build_object(
             'de', 'Anmeldungsdaten für die Direktzahlungsarten, den ÖLN und die Kontrollstellen',
             'fr', 'Données d’inscription pour les types de paiements directs, les PER et les organes de contrôle',
             'it', 'Dati di notifica per tipi di pagamenti diretti, per la PER e per gli organi di controllo'),
             Jsonb_build_object(
             'de','Dieses Datenprodukt enthält die Anmeldedaten für die Direktzahlungsprogramme, für den Ökologischen Leistungsnachweis (ÖLN) sowie die Kontrollstelle.',
             'fr','Ce produit contient les données d’inscription pour les programmes des paiements directs, les prestations écologiques requises (PER) et les organes de contrôle.',
             'it','Questo prodotto contiene i dati di notifica per i programmi dei pagamenti diretti, per la prova che le esigenze ecologiche sono rispettate (PER) e per gli organi di controllo.'),
             'AGIS_ECO_ETHO_V1',
             'POST',
             'ecoetho',
             '{"registrationYear":"{{year}}","ids":{"uid":"{{uid}}"},"dataRequestType":{"finalData":false}}')
