UPDATE public.notification_template
SET email_text = '{
        "de": "<p>Guten Tag</p><p>Ein neuer Antrag wurde zur Kontrolle eingereicht. Bitte prüfen Sie diesen im Admin-Portal.</p><p><strong>Zusammenfassung:</strong></p><ul><li><strong>{{dataRequestTitleDe}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Bezüger: <strong>{{dataConsumer}}</strong></li></ul><p>Hier gelangen Sie direkt zum Antrag: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Antrag öffnen</a></p><p>Freundliche Grüsse<br>Ihr agridata.ch-Team</p>",
        "fr": "<p>Bonjour</p><p>Une nouvelle demande a été soumise pour vérification. Veuillez la consulter dans le portail d’administration.</p><p><strong>Résumé:</strong></p><ul><li><strong>{{dataRequestTitleFr}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Demandeur: <strong>{{dataConsumer}}</strong></li></ul><p>Accédez directement à la demande ici: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Ouvrir la demande</a></p><p>Cordialement,<br>l''équipe de agridata.ch</p>",
        "it": "<p>Buongiorno</p><p>Una nuova richiesta è stata inviata per la verifica. La preghiamo di controllarla nel portale amministrativo.</p><p><strong>Riepilogo:</strong></p><ul><li><strong>{{dataRequestTitleIt}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Richiedente: <strong>{{dataConsumer}}</strong></li></ul><p>Può visualizzare la richiesta qui: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Apri la richiesta</a></p><p>Cordiali saluti,<br>il team di agridata.ch</p>"
    }'
WHERE event_type_code = 'DATA_REQUEST_READY_FOR_REVIEW';

UPDATE public.notification_template
SET email_text = '{
      "de": "<p>Guten Tag</p><p>Der Datenbezüger {{dataConsumer}} möchte gerne Daten von Ihnen beziehen und hat hierzu einen Antrag auf agridata.ch gestellt.</p><p>Damit der Datenantrag aktiviert werden kann, wird noch Ihre Zustimmung benötigt. Der vom Bezüger bereits unterzeichnete Vertrag liegt zur Prüfung und Gegenzeichnung für Sie bereit.</p><p><strong>Zusammenfassung:</strong></p><ul><li><strong>{{dataRequestTitleDe}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Datenbezüger: <strong>{{dataConsumer}}</strong></li></ul><p>Sie können den Antrag hier einsehen und direkt online unterzeichnen: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Antrag öffnen</a></p><p>Bei Fragen zum Inhalt wenden Sie sich bitte direkt an {{dataConsumer}}. Bei technischen Fragen steht Ihnen unser Support gerne zur Verfügung.</p><p>Freundliche Grüsse<br>Ihr agridata.ch-Team</p>",
      "fr": "<p>Bonjour</p><p>Le demandeur de données {{dataConsumer}} souhaite obtenir des données de votre part et a déposé une demande à cet effet sur agridata.ch.</p><p>Pour que la demande de données puisse être activée, votre accord est encore nécessaire. Le contrat, déjà signé par le demandeur, est à votre disposition pour examen et contre-seing.</p><p><strong>Résumé:</strong></p><ul><li><strong>{{dataRequestTitleFr}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Demandeur: <strong>{{dataConsumer}}</strong></li></ul><p>Vous pouvez consulter la demande ici et la signer directement en ligne: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Ouvrir la demande</a></p><p>Pour toute question sur le contenu, veuillez contacter directement {{dataConsumer}}. En cas de questions techniques, notre support se tient volontiers à votre disposition.</p><p>Cordialement,<br>l''équipe de agridata.ch</p>",
      "it": "<p>Buongiorno</p><p>Il richiedente dei dati {{dataConsumer}} desidera ricevere dati da lei e ha presentato una richiesta in tal senso su agridata.ch.</p><p>Affinché la richiesta dati possa essere attivata, è ancora necessario il suo consenso. Il contratto, già firmato dal richiedente, è pronto per la sua revisione e controfirma.</p><p><strong>Riepilogo:</strong></p><ul><li><strong>{{dataRequestTitleIt}}</strong> (ID: {{dataRequestHumanFriendlyId}})</li><li>Richiedente: <strong>{{dataConsumer}}</strong></li></ul><p>Può visualizzare la richiesta qui e firmarla direttamente online: <a href=\"{{dataRequestUrl}}\" target=\"_blank\" rel=\"noopener noreferrer\">Apri la richiesta</a></p><p>Per domande sul contenuto, la preghiamo di contattare direttamente {{dataConsumer}}. In caso di domande tecniche, il nostro supporto è volentieri a sua disposizione.</p><p>Cordiali saluti,<br>il team di agridata.ch</p>"
    }'
WHERE event_type_code = 'DATA_REQUEST_READY_FOR_PROVIDER_SIGNING';
