DELETE FROM data_product;

INSERT INTO data_product (id, archived, created_at, modified_at, data_source_system_code, name, description) VALUES
('c661ea48-106d-4d7a-a5d1-a9a6db48dd8c'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'R01', 'fr', 'R01', 'it', 'R01'), jsonb_build_object('de', 'Dieses Datenpaket enthält von Tierhaltern und Bewirtschaftern Angaben zur Person', 'fr', 'Ce paquet de données contient des informations personnelles sur les détenteurs d’animaux et les exploitants.', 'it', 'Questo pacchetto di dati contiene informazioni personali sui detentori di animali e sui gestori.')),
('147e8c40-78cc-4db3-a909-65504aa62a64'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'R02', 'fr', 'R02', 'it', 'R02'), jsonb_build_object('de', 'Dieses Datenpaket enthält allgemeine Informationen zu Betrieben von Tierhaltern und Bewirtschaftern', 'fr', 'Ce paquet de données contient des informations générales sur les exploitations des détenteurs d’animaux et des exploitants.', 'it', 'Questo pacchetto di dati contiene informazioni generali sulle aziende dei detentori di animali e dei gestori.')),
('254bb1f1-05d3-4c4e-80ea-2fa075771ed7'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'R03', 'fr', 'R03', 'it', 'R03'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Beziehungen von den Betrieben zu seinen über-/untergeordneten Betrieben', 'fr', 'Ce paquet de données contient les relations entre les exploitations et leurs exploitations supérieures ou subordonnées.', 'it', 'Questo pacchetto di dati contiene le relazioni tra le aziende e le loro aziende superiori o subordinate.')),
('085e4b72-964d-4bd5-a3c9-224d8c5585af'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S01', 'fr', 'S01', 'it', 'S01'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Art und Anzahl Nutztiere, die auf einem Betrieb gehalten werden. ', 'fr', 'Ce paquet de données contient le type et le nombre d’animaux de rente détenus sur une exploitation.', 'it', 'Questo pacchetto di dati contiene il tipo e il numero di animali da reddito presenti in un’azienda agricola.')),
('a795d0b0-f177-4bb4-8e41-1ed12d358c79'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S02', 'fr', 'S02', 'it', 'S02'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Art und Anzahl Nutztiere pro Betrieb, die im Inland gesömmert wurden.', 'fr', 'Ce paquet de données contient le type et le nombre d’animaux estivés par exploitation sur le territoire national.', 'it', 'Questo pacchetto di dati contiene il tipo e il numero di animali alpeggiati per azienda sul territorio nazionale.')),
('0a808700-d89e-4fa0-a2b8-8edb15f3addd'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S03', 'fr', 'S03', 'it', 'S03'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Fläche der im entsprechenden Jahr angebauten Hauptkulturen eines Betriebs', 'fr', 'Ce paquet de données contient la surface des principales cultures cultivées par une exploitation au cours de l’année correspondante.', 'it', 'Questo pacchetto di dati contiene la superficie delle colture principali coltivate da un’azienda agricola nell’anno di riferimento.')),
('ef4f42dd-eaa9-4af1-988c-86b47bd963fe'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S04', 'fr', 'S04', 'it', 'S04'), jsonb_build_object('de', 'Dieses Datenpaket enthält Flächen, die in einem Hang liegen mit einer Neigung grösser als 18%', 'fr', 'Ce paquet de données contient les surfaces situées sur une pente avec une inclinaison supérieure à 18 %.', 'it', 'Questo pacchetto di dati contiene le superfici situate su un pendio con pendenza superiore al 18%.')),
('2375219c-5fe3-458f-bd07-d3c2c87e2539'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S05', 'fr', 'S05', 'it', 'S05'), jsonb_build_object('de', 'Dieses Datenpaket enthält Rebflächen, die in einem Hang liegen mit einer Neigung grösser als 30%', 'fr', 'Ce paquet de données contient des surfaces viticoles situées sur des pentes avec une inclinaison supérieure à 30 %.', 'it', 'Questo pacchetto di dati contiene superfici vitate situate su pendii con pendenza superiore al 30%.')),
('64e39df0-2e56-4204-9c44-a43e1e26a2e8'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S06', 'fr', 'S06', 'it', 'S06'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Daten zu den Biodiversitätsförderflächen gemäss Direktzahlungsverordnung (DZV)', 'fr', 'Ce paquet de données contient les données relatives aux surfaces de promotion de la biodiversité selon l’Ordonnance sur les paiements directs (OPD).', 'it', 'Questo pacchetto di dati contiene i dati sulle superfici per la promozione della biodiversità secondo l’Ordinanza sui pagamenti diretti (OPD).')),
('1dad9f91-30d8-45c9-8c82-ad72f4cb22e7'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'S07', 'fr', 'S07', 'it', 'S07'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Daten zu den Vernetzungsflächen gemäss Direktzahlungsverordnung (DZV)', 'fr', 'Ce paquet de données contient les données relatives aux surfaces de mise en réseau selon l’Ordonnance sur les paiements directs (OPD).', 'it', 'Questo pacchetto di dati contiene i dati sulle superfici di messa in rete secondo l’Ordinanza sui pagamenti diretti (OPD).')),
('46f8a883-da7c-49b3-b986-10a24b1e09ef'::uuid, false, NOW(), NOW(), 'AGIS', jsonb_build_object('de', 'A01', 'fr', 'A01', 'it', 'A01'), jsonb_build_object('de', 'Dieses Datenpaket enthält die Anmeldedaten für die Direktzahlungsprogramme, für den Ökologischen Leistungsnachweis (ÖLN) sowie die Kontrollstelle', 'fr', 'Ce paquet de données contient les données d’inscription aux programmes de paiements directs, à la preuve du respect des exigences écologiques (PER) et à l’organisme de contrôle.', 'it', 'Questo pacchetto di dati contiene i dati di iscrizione ai programmi di pagamenti diretti, alla prova del rispetto delle esigenze ecologiche (PRE) e all’organismo di controllo.'));
