-- ===============================================
-- data_products
-- ===============================================
INSERT INTO data_product (
    id,
    archived,
    created_at,
    modified_at,
    data_source_system_id,
    name,
    description,
    rest_client_identifier_code,
    rest_client_method_code,
    rest_client_path_template,
    rest_client_request_template,
    flow_code,
    deprecated_since
)
VALUES (
--  ZO-API
    '2f28d2ec-8797-46fd-8149-9c70ac5f2ebe'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbewegungsdaten Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Rindern innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht, Missbildungen und Meldungen. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_CattleDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '0b42afb7-3683-4065-9cb3-396995a5be97'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderdetail Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Rinderdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Nachkommen, Missbildungen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/{{eartagNumber}}?dataPackage=ZOAPI_CattleDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'd10b898f-9796-4993-9654-8f092b97989d'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Rinderbestand Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Rinderbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Missbildungen, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Rinderzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/cattle/livestock?dataPackage=ZOAPI_CattleLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '59115547-cfd5-428a-9863-6cd1b2200013'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Tierhaltungsdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält Tierhaltungsdaten für eine spezifische BUR-Nr. Es umfasst die Adresse und andere betriebsspezifische Daten der Tierhaltung.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/localunits/{{bur}}?dataPackage=ZOAPI_FarmDataV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    'ec5b9f05-0b8d-4833-9447-d7338fe1dc78'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Bewirtschafterdaten', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Bewirtschafter für eine spezifische BUR-Nr. Es umfasst personenbezogene Daten des Bewirtschafters.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/localunits/{{bur}}/legalunit?dataPackage=ZOAPI_FarmManagerV1&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '88dcf0f9-8502-4596-b035-45c5d548d262'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegenbewegungsdaten Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Ziegen innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht und Meldungen. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_GoatDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    '54decb00-cecd-4c64-b368-8ab999130ac4'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegendetail Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Ziegendaten für eine spezifische Ohrmarke und umfasst die Basisinformationen des Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Nachkommen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat/{{eartagNumber}}?dataPackage=ZOAPI_GoatDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'd156f252-c8c0-49de-8541-149c35aada6c'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Ziegenbestand Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Ziegenbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Ziegenzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/goat/livestock?dataPackage=ZOAPI_GoatLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL),
    (
    '720aa209-7aa8-4faf-8b1a-013a041084f2'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafbewegungsdaten Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Bewegungsdaten von ZO-zugewiesenen Schafen innerhalb eines definierten Zeitraums (von–bis). Es umfasst aktualisierte Basisinformationen sowie Angaben zu Standort, Eltern, Zucht und Meldungen. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep?dateFrom={{dateFrom}}&dateTo={{dateTo}}&dataPackage=ZOAPI_SheepDeltaV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'b0a4ff29-cac4-4413-b8fb-7ff61f4ff2ac'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafdetail Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält die Schafdaten für eine spezifische Ohrmarke. Es umfasst die Basisinformationen des abgefragten Tieres. Zusätzlich werden Angaben zu Standort, Eltern, Krankheiten, Zucht, Nachkommen, Meldungen, Aufenthalte und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep/{{eartagNumber}}?dataPackage=ZOAPI_SheepDetailV1&recipientUid={{recipientUid}}',
    NULL,
    'UNBOUND_POST_VALIDATION',
    NULL),
    (
    'e6128e10-5d2b-4096-8356-b6523cb30e92'::uuid,
    false,
    NOW(),
    NOW(),
    'e93f1023-850d-4188-bf40-50e5eedaaa57',
    jsonb_build_object('de', 'Schafbestand Zucht', 'fr', 'tbd', 'it', 'tbd'),
    jsonb_build_object('de', 'Dieses Datenpaket enthält den aktuellen Schafbestand für eine spezifische BUR-Nr. Es umfasst den Bestand sowie die Basisinformationen der Tiere. Zusätzlich werden Angaben zu Standort, Eltern, Zucht, Meldungen und der Stammbetriebsgeschichte geliefert. Das Datenpaket ist den Schafzuchtorganisationen vorbehalten.', 'fr', 'tbd', 'it', 'tbd'),
    'TVD_ZO_API',
    'GET',
    'api-zo/v1.0/shared-data/sheep/livestock?dataPackage=ZOAPI_SheepLivestockV1&localUnitNumber={{bur}}&recipientUid={{recipientUid}}',
    NULL,
    'BUR_BASED_POST_VALIDATION',
    NULL)
ON CONFLICT (id) DO UPDATE
SET
    archived = EXCLUDED.archived,
    created_at = EXCLUDED.created_at,
    modified_at = EXCLUDED.modified_at,
    data_source_system_id = EXCLUDED.data_source_system_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    rest_client_identifier_code = EXCLUDED.rest_client_identifier_code,
    rest_client_method_code = EXCLUDED.rest_client_method_code,
    rest_client_path_template = EXCLUDED.rest_client_path_template,
    rest_client_request_template = EXCLUDED.rest_client_request_template,
    flow_code = EXCLUDED.flow_code,
    deprecated_since = EXCLUDED.deprecated_since;
