POST {{baseUrl}}/test-data/reset
Authorization: Bearer {{$auth.token("admin")}}
Content-Type: application/json

> {%
  client.test("Create a new data request", function () {
    client.assert(response.status === 204, "Expected Response status is 204, got: " + response.status)
  })
%}
